### ISSUE TITLE
missing core features

### ISSUE THREAD

**Issue by infinicore** [ryanrocks462/RinNand#1]
There is nothing in the repository right now. In particular, the bootrom dumper is missing.

Is there any ETA or are you bullshitting us again, Ryan?

**Comment by ryanrocks462** [comment]
Is it not possible to sleep ;~; this was created at like 1am lol
Plus it's hard to edit rn cause school atm QQ

**Comment by Sterillo** [comment]
"school"
If you are in Grade school I am totally not expecting much of this. If you could make it work I will be amazed.

**Comment by ryanrocks462** [comment]
Nigga I'm a junior in highschool :^) asides if u kept up with gbafags you would know what RinNand really is bb
